### ISSUE TITLE
AssertionError: No transcripts in training data

### ISSUE THREAD

**Issue by DanielAldas** [TRISTAN-ORF/RiboTIE#10]
I am having a new problem now. 
I got the following error during finetuning: 

<img width="1502" alt="Screenshot 2024-05-24 at 3 49 55 PM" src="https://github.com/TRISTAN-ORF/RiboTIE/assets/54075272/374327be-f360-4906-bfda-2f3227e3a650">

I don't know what the cause could be this time. Thanks!

**Comment by jdcla** [comment]
Hey Daniel, 
Thanks for the feedback. These reports help me fix up some functionalities I hadn't thought of before.
The problem here is that the pretrained model has different chromsome names than the assembly used by you. (1,2,3,4) vs (chr1, chr2, chr3, ...). The tool searches for transcripts on (1). 

I'll have to create some library that automatically detects and recognizes multiple variants of the same chromosome names. I'll get to this next week. A quick hack would be to rename your main chromosomes in the gtf and fa files if you'd want a solution ASAP.

**Comment by jdcla** [comment]
Actually, that was bad advice, as that might give complications with the alignment in the bam.

A hack would be to copy the pre trained model weights and configuration file from the package (transcript_transformer/pre trained/ribotie/...) and alter the chromosome names in the yaml file to the ones of your assembly.

You can reference to this edited yaml.

Otherwise, I'll check this next week so if you're not in a hurry this will work soon

**Comment by DanielAldas** [comment]
Thanks for your advice, I am glad I'm being helpful!
I will wait for you to upload the update as I am not in a hurry to run it

**Comment by jdcla** [comment]
This should be fixed in the latest release of `transcript-transformer` (v0.8.4)
