### ISSUE TITLE
Combinning multiple dataset for better precision and faster computing

### ISSUE THREAD

**Issue by NicolasProvencher** [TRISTAN-ORF/RiboTIE#7]
Hi,
I have gone through your new bioarxiv article. I was wondering if the results shown in `"supplementary table a10: RIBO-former performances for merged data sets."` were still viable since it seemed to no be published in the new release. I am interested since I have already ran riboformer(ribotie now) on riboseq libraries merged after alignment when they had the same experimental setting (cell type, study, drug used) and was wondering if it was preferable to rerun everything without any merging.

**Comment by jdcla** [comment]
Hey Nicolas,

Yes, it is viable to merge datasets for Ribo-seq processing under the right circumstances. For example, merging multiple replicate samples generated in the same study will increase read depth and should return more called translated ORFs.

You definitely don't have to re-run everything. The question on whether it is better to process samples independently or using merged samples is related to your study objective rather than the translated ORF caller tool you're using. Both approaches are valid for RiboTIE.
